ignore:
  - "src/main/java/br/com/victor/smite/configuration"  # ignore folders and all its contents
  - "src/main/java/br/com/victor/smite/entity"  # ignore folders and all its contents
  - "src/main/java/br/com/victor/smite/security"  # ignore folders and all its contents

coverage:
        precision: 1
        range: 70...100

        status:
                project:
                        default:
                                enabled: yes
                                threshold: 1
                                if_not_found: success
                                if_no_updates: success
                patch:
                        default:
                                threshold: 10

comment:
        behavior: new
